apiVersion: apps/v1
kind: Deployment
metadata:
  name: internet-protocol
spec:
  replicas: 1
  selector:
    matchLabels:
      app: internet-protocol
  template:
    metadata:
      labels:
        app: internet-protocol
    spec:
      containers:
        - name: internet-protocol
          image: ghcr.io/hatrongvu13/telegram-noti:1acf238f0694c4704132e943c6dec408d4e9a25e
          imagePullPolicy: Always
          env:
            - name: BOT_TOKEN
              value: ""
      imagePullSecrets:
        - name: ghcr-secret  # Sử dụng Secret đã tạo
---
apiVersion: v1
kind: Service
metadata:
  name: internet-protocol
spec:
  type: LoadBalancer
  ports:
    - port: 8090
      targetPort: 8080
  selector:
    app: internet-protocol