apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-pvc-jenkins
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi  # Chỉ định dung lượng bạn muốn yêu cầu
  storageClassName: manual  # Tên StorageClass cần trùng với PV