#apiVersion: v1
#kind: PersistentVolumeClaim
#metadata:
#  name: local-pvc-dind
#spec:
#  accessModes:
#    - ReadWriteOnce
#  resources:
#    requests:
#      storage: 50Gi  # Chỉ định dung lượng bạn muốn yêu cầu
#  storageClassName: manual  # Tên StorageClass cần trùng với PV
---
apiVersion: v1
kind: Pod
metadata:
  name: dind
  labels:
    app: dind
spec:
  containers:
    - name: dind
      image: docker:dind
      securityContext:
        privileged: true
      ports:
        - containerPort: 2375
          protocol: TCP
      env:
        - name: DOCKER_TLS_CERTDIR
          value: ""
#      volumeMounts:
#        - mountPath: /var/lib/docker
#          name: local-dind
#  volumes:
#    - name: local-dind
#      persistentVolumeClaim:
#        claimName: local-pvc-dind
---
apiVersion: v1
kind: Service
metadata:
  name: dind
spec:
  type: ClusterIP
  ports:
    - port: 2375
      targetPort: 2375
  selector:
    app: dind