apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi  # Chỉ định dung lượng bạn muốn yêu cầu
  storageClassName: nfs-storage  # Tên StorageClass cần trùng với PV
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      containers:
        - name: jenkins
          image: jenkins/jenkins:lts-jdk17
          ports:
            - containerPort: 8080
            - containerPort: 50000
          volumeMounts:
            - mountPath: /var/jenkins_home
              name: local-jenkins
          securityContext:
            runAsUser: 0 # user root
          env:
            - name: DOCKER_HOST
              value: "tcp://dind:2375"
      volumes:
        - name: local-jenkins
          persistentVolumeClaim:
            claimName: jenkins-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: jenkins
spec:
  type: LoadBalancer
  ports:
    - port: 9090
      targetPort: 8080
  selector:
    app: jenkins