apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-pv-rstp
spec:
  capacity:
    storage: 5Gi  # Dung lượng ổ cứng
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce  # Có thể chỉnh thành ReadWriteMany nếu cần
  persistentVolumeReclaimPolicy: Retain
  storageClassName: rstp-pv
  local:
    path: /mnt/data/rstp  # Đường dẫn đến ổ cứng được mount
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - jaxpi4  # Tên của node mà ổ cứng đã được gắn vào
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-pvc-rstp
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi  # Chỉ định dung lượng bạn muốn yêu cầu
  storageClassName: rstp-pv  # Tên StorageClass cần trùng với PV