apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-pv-registry
spec:
  capacity:
    storage: 15Gi  # Dung lượng ổ cứng
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce  # Có thể chỉnh thành ReadWriteMany nếu cần
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-path
  local:
    path: /mnt/data/registry  # Đường dẫn đến ổ cứng được mount
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - jaxpi4  # Tên của node mà ổ cứng đã được gắn vào
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-pvc-registry
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 15Gi  # Chỉ định dung lượng bạn muốn yêu cầu
  storageClassName: local-path  # Tên StorageClass cần trùng với PV